"use client";

import * as XLSX from "xlsx";
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from "sonner";

export type ExportFormat = "pdf" | "excel";

export interface ExportColumn<T> {
  header: string;
  value: (row: T) => string | number | null | undefined;
}

export interface ExportMeta {
  title: string;
  /** Audit: who triggered the export (app_admin username) */
  exportedBy: string;
  /** Date range applied to the dataset */
  periodLabel: string;
  /** Optional secondary filters applied (e.g. "DBA: alice, Shift: 1") */
  filterLabel?: string;
}

function timestampNow(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())} ${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
}

function fileStamp(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}${pad(d.getMonth() + 1)}${pad(d.getDate())}_${pad(d.getHours())}${pad(d.getMinutes())}`;
}

export function exportDataset<T>(
  format: ExportFormat,
  columns: ExportColumn<T>[],
  rows: T[],
  meta: ExportMeta
): void {
  if (rows.length === 0) {
    toast.error("No data to export.");
    return;
  }
  if (format === "excel") {
    exportExcel(columns, rows, meta);
  } else {
    exportPdf(columns, rows, meta);
  }
}

function exportExcel<T>(columns: ExportColumn<T>[], rows: T[], meta: ExportMeta): void {
  const wb = XLSX.utils.book_new();

  const headerRow = columns.map((c) => c.header);
  const bodyRows = rows.map((r) => columns.map((c) => c.value(r) ?? ""));

  const auditRows: (string | number)[][] = [
    [meta.title],
    ["Exported By", meta.exportedBy],
    ["Exported At", timestampNow()],
    ["Period", meta.periodLabel],
    ["Filters", meta.filterLabel || "—"],
    [],
    headerRow,
    ...bodyRows
  ];

  const ws = XLSX.utils.aoa_to_sheet(auditRows);
  ws["!cols"] = columns.map((c) => ({ wch: Math.max(14, c.header.length + 4) }));
  ws["!merges"] = [{ s: { r: 0, c: 0 }, e: { r: 0, c: Math.max(0, headerRow.length - 1) } }];

  XLSX.utils.book_append_sheet(wb, ws, "Report");

  const wbout = XLSX.write(wb, { bookType: "xlsx", type: "array" });
  const blob = new Blob([wbout], { type: "application/octet-stream" });
  triggerDownload(blob, `${meta.title}-${fileStamp()}.xlsx`);
}

function exportPdf<T>(columns: ExportColumn<T>[], rows: T[], meta: ExportMeta): void {
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFontSize(16);
  doc.setTextColor(20, 30, 45);
  doc.text(meta.title, 40, 40);

  doc.setFontSize(9);
  doc.setTextColor(90, 100, 115);
  doc.text(`Exported By: ${meta.exportedBy}`, 40, 58);
  doc.text(`Exported At: ${timestampNow()}`, 40, 70);
  const rightX = pageWidth - 40;
  doc.text(`Period: ${meta.periodLabel}`, rightX, 58, { align: "right" });
  doc.text(`Filters: ${meta.filterLabel || "—"}`, rightX, 70, { align: "right" });

  const head = [columns.map((c) => c.header)];
  const body = rows.map((r) => columns.map((c) => String(c.value(r) ?? "—")));

  autoTable(doc, {
    startY: 86,
    head,
    body,
    styles: { fontSize: 8, cellPadding: 3, overflow: "linebreak" },
    headStyles: { fillColor: [18, 23, 34], textColor: [35, 211, 238], fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 247, 250] },
    margin: { left: 40, right: 40 },
    didDrawPage: () => {
      const page = doc.getNumberOfPages();
      doc.setFontSize(8);
      doc.setTextColor(120, 130, 140);
      doc.text(
        `Page ${page} • Generated by DBA Console • ${timestampNow()}`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 16,
        { align: "center" }
      );
    }
  });

  doc.save(`${meta.title}-${fileStamp()}.pdf`);
}

function triggerDownload(blob: Blob, filename: string): void {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
