SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

-- Tables for the n8n check_performance workflow.
-- Use one run_group_id value for every row produced by the same RUN ALL request.
-- A good value is the n8n request_id returned to the app, for example N8N-20260604-001.

CREATE TABLE app_perf_run_summary (
  perf_run_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id        VARCHAR2(128) NOT NULL,
  external_request_id VARCHAR2(128),
  requested_by        VARCHAR2(128) NOT NULL,
  db_name             VARCHAR2(64) NOT NULL,
  run_status          VARCHAR2(32) DEFAULT 'success' NOT NULL,
  ai_summary          CLOB,
  llm_output          CLOB,
  raw_output          CLOB,
  created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_run_summary_pk PRIMARY KEY (perf_run_id),
  CONSTRAINT app_perf_run_summary_uk UNIQUE (run_group_id),
  CONSTRAINT app_perf_run_status_ck CHECK (run_status IN ('success', 'error', 'partial'))
);

CREATE INDEX app_perf_run_sum_db_ix ON app_perf_run_summary (db_name, created_at);
CREATE INDEX app_perf_run_sum_req_ix ON app_perf_run_summary (requested_by, created_at);

CREATE TABLE app_perf_top_sql (
  top_sql_row_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id        VARCHAR2(128) NOT NULL,
  requested_by        VARCHAR2(128) NOT NULL,
  db_name             VARCHAR2(64) NOT NULL,
  sql_id              VARCHAR2(32),
  plan_hash_value     NUMBER,
  parsing_schema_name VARCHAR2(128),
  module_name         VARCHAR2(255),
  executions          NUMBER,
  elapsed_sec         NUMBER,
  cpu_sec             NUMBER,
  buffer_gets         NUMBER,
  disk_reads          NUMBER,
  rows_processed      NUMBER,
  sql_text            CLOB,
  raw_row_json        CLOB,
  created_at          TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_top_sql_pk PRIMARY KEY (top_sql_row_id)
);

CREATE INDEX app_perf_top_sql_run_ix ON app_perf_top_sql (run_group_id);
CREATE INDEX app_perf_top_sql_db_ix ON app_perf_top_sql (db_name, created_at);
CREATE INDEX app_perf_top_sql_req_ix ON app_perf_top_sql (requested_by, created_at);

CREATE TABLE app_perf_cpu_usage (
  cpu_row_id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id            VARCHAR2(128) NOT NULL,
  requested_by            VARCHAR2(128) NOT NULL,
  db_name                 VARCHAR2(64) NOT NULL,
  num_cpus                NUMBER,
  current_total_cpu_util  NUMBER,
  user_cpu_util           NUMBER,
  system_cpu_util         NUMBER,
  busy_time               NUMBER,
  idle_time               NUMBER,
  raw_row_json            CLOB,
  created_at              TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_cpu_usage_pk PRIMARY KEY (cpu_row_id)
);

CREATE INDEX app_perf_cpu_run_ix ON app_perf_cpu_usage (run_group_id);
CREATE INDEX app_perf_cpu_db_ix ON app_perf_cpu_usage (db_name, created_at);
CREATE INDEX app_perf_cpu_req_ix ON app_perf_cpu_usage (requested_by, created_at);

CREATE TABLE app_perf_wait_events (
  wait_event_row_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id       VARCHAR2(128) NOT NULL,
  requested_by       VARCHAR2(128) NOT NULL,
  db_name            VARCHAR2(64) NOT NULL,
  event_name         VARCHAR2(255),
  wait_class         VARCHAR2(128),
  total_waits        NUMBER,
  time_waited_sec    NUMBER,
  avg_wait_cs        NUMBER,
  raw_row_json       CLOB,
  created_at         TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_wait_events_pk PRIMARY KEY (wait_event_row_id)
);

CREATE INDEX app_perf_wait_run_ix ON app_perf_wait_events (run_group_id);
CREATE INDEX app_perf_wait_db_ix ON app_perf_wait_events (db_name, created_at);
CREATE INDEX app_perf_wait_req_ix ON app_perf_wait_events (requested_by, created_at);

CREATE TABLE app_perf_session_longops (
  longops_row_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id     VARCHAR2(128) NOT NULL,
  requested_by     VARCHAR2(128) NOT NULL,
  db_name          VARCHAR2(64) NOT NULL,
  sid              NUMBER,
  serial_num       NUMBER,
  db_username      VARCHAR2(128),
  sql_id           VARCHAR2(32),
  operation_name   VARCHAR2(255),
  pct_done         NUMBER,
  elapsed_min      NUMBER,
  eta_min          NUMBER,
  raw_row_json     CLOB,
  created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_longops_pk PRIMARY KEY (longops_row_id)
);

CREATE INDEX app_perf_longops_run_ix ON app_perf_session_longops (run_group_id);
CREATE INDEX app_perf_longops_db_ix ON app_perf_session_longops (db_name, created_at);
CREATE INDEX app_perf_longops_req_ix ON app_perf_session_longops (requested_by, created_at);

CREATE TABLE app_perf_invalid_objects (
  invalid_row_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id     VARCHAR2(128) NOT NULL,
  requested_by     VARCHAR2(128) NOT NULL,
  db_name          VARCHAR2(64) NOT NULL,
  owner_name       VARCHAR2(128),
  object_type      VARCHAR2(128),
  object_name      VARCHAR2(255),
  object_status    VARCHAR2(32),
  last_ddl_time    TIMESTAMP(6),
  raw_row_json     CLOB,
  created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_invalid_pk PRIMARY KEY (invalid_row_id)
);

CREATE INDEX app_perf_invalid_run_ix ON app_perf_invalid_objects (run_group_id);
CREATE INDEX app_perf_invalid_db_ix ON app_perf_invalid_objects (db_name, created_at);
CREATE INDEX app_perf_invalid_req_ix ON app_perf_invalid_objects (requested_by, created_at);

CREATE TABLE app_perf_sessions (
  session_row_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id     VARCHAR2(128) NOT NULL,
  requested_by     VARCHAR2(128) NOT NULL,
  db_name          VARCHAR2(64) NOT NULL,
  sid              NUMBER,
  serial_num       NUMBER,
  db_username      VARCHAR2(128),
  os_user          VARCHAR2(128),
  machine_name     VARCHAR2(255),
  program_name     VARCHAR2(255),
  sql_id           VARCHAR2(32),
  event_name       VARCHAR2(255),
  session_state    VARCHAR2(64),
  session_status   VARCHAR2(32),
  seconds_in_wait  NUMBER,
  last_call_et     NUMBER,
  raw_row_json     CLOB,
  created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_sessions_pk PRIMARY KEY (session_row_id)
);

CREATE INDEX app_perf_sessions_run_ix ON app_perf_sessions (run_group_id);
CREATE INDEX app_perf_sessions_db_ix ON app_perf_sessions (db_name, created_at);
CREATE INDEX app_perf_sessions_req_ix ON app_perf_sessions (requested_by, created_at);

CREATE TABLE app_perf_locks (
  lock_row_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id     VARCHAR2(128) NOT NULL,
  requested_by     VARCHAR2(128) NOT NULL,
  db_name          VARCHAR2(64) NOT NULL,
  waiter_sid       NUMBER,
  waiter_serial    NUMBER,
  waiter_user      VARCHAR2(128),
  waiter_sql_id    VARCHAR2(32),
  blocker_sid      NUMBER,
  blocker_serial   NUMBER,
  blocker_user     VARCHAR2(128),
  blocker_sql_id   VARCHAR2(32),
  waiting_min      NUMBER,
  event_name       VARCHAR2(255),
  raw_row_json     CLOB,
  created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_locks_pk PRIMARY KEY (lock_row_id)
);

CREATE INDEX app_perf_locks_run_ix ON app_perf_locks (run_group_id);
CREATE INDEX app_perf_locks_db_ix ON app_perf_locks (db_name, created_at);
CREATE INDEX app_perf_locks_req_ix ON app_perf_locks (requested_by, created_at);

CREATE TABLE app_perf_long_queries (
  long_query_row_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  run_group_id      VARCHAR2(128) NOT NULL,
  requested_by      VARCHAR2(128) NOT NULL,
  db_name           VARCHAR2(64) NOT NULL,
  sid               NUMBER,
  serial_num        NUMBER,
  db_username       VARCHAR2(128),
  machine_name      VARCHAR2(255),
  running_seconds   NUMBER,
  sql_id            VARCHAR2(32),
  sql_text          CLOB,
  raw_row_json      CLOB,
  created_at        TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_perf_long_queries_pk PRIMARY KEY (long_query_row_id)
);

CREATE INDEX app_perf_longqry_run_ix ON app_perf_long_queries (run_group_id);
CREATE INDEX app_perf_longqry_db_ix ON app_perf_long_queries (db_name, created_at);
CREATE INDEX app_perf_longqry_req_ix ON app_perf_long_queries (requested_by, created_at);

COMMIT;
PROMPT Performance tuning tables created successfully.
