SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--------------------------------------------------------------------------------
-- 1) Run this block as SYS or SYSTEM once to create the schema user.
--------------------------------------------------------------------------------
-- CREATE USER APP_DBA IDENTIFIED BY Password123;
-- GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE TRIGGER TO APP_DBA;
-- ALTER USER APP_DBA QUOTA UNLIMITED ON USERS;

--------------------------------------------------------------------------------
-- 2) Connect as APP_DBA and run the remaining commands.
--------------------------------------------------------------------------------
-- CONNECT APP_DBA/Password123@localhost:1522/TEST;

CREATE TABLE app_users (
  user_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  username VARCHAR2(128) NOT NULL,
  password_salt VARCHAR2(128) NOT NULL,
  password_hash VARCHAR2(64) NOT NULL,
  api_token_hash VARCHAR2(64),
  role VARCHAR2(20) DEFAULT 'operator' NOT NULL,
  is_active CHAR(1) DEFAULT 'Y' NOT NULL,
  failed_login_count NUMBER DEFAULT 0 NOT NULL,
  locked_until TIMESTAMP(6),
  last_login_at TIMESTAMP(6),
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_users_pk PRIMARY KEY (user_id),
  CONSTRAINT app_users_username_uk UNIQUE (username),
  CONSTRAINT app_users_role_ck CHECK (role IN ('dba_admin', 'operator', 'auditor')),
  CONSTRAINT app_users_is_active_ck CHECK (is_active IN ('Y', 'N'))
);

CREATE OR REPLACE TRIGGER app_users_bu_trg
BEFORE UPDATE ON app_users
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE app_sessions (
  session_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  session_token_hash VARCHAR2(64) NOT NULL,
  user_id NUMBER NOT NULL,
  auth_mode VARCHAR2(10) NOT NULL,
  expires_at TIMESTAMP(6) NOT NULL,
  revoked_at TIMESTAMP(6),
  ip_address VARCHAR2(64),
  user_agent VARCHAR2(512),
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_sessions_pk PRIMARY KEY (session_id),
  CONSTRAINT app_sessions_token_uk UNIQUE (session_token_hash),
  CONSTRAINT app_sessions_user_fk FOREIGN KEY (user_id) REFERENCES app_users(user_id),
  CONSTRAINT app_sessions_auth_mode_ck CHECK (auth_mode IN ('jwt', 'token'))
);

CREATE INDEX app_sessions_user_ix ON app_sessions (user_id);
CREATE INDEX app_sessions_exp_ix ON app_sessions (expires_at);

CREATE TABLE app_audit_logs (
  audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  user_id NUMBER,
  actor VARCHAR2(128) NOT NULL,
  action VARCHAR2(64) NOT NULL,
  db_name VARCHAR2(64),
  status VARCHAR2(32) NOT NULL,
  detail CLOB,
  metadata_json CLOB,
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_audit_logs_pk PRIMARY KEY (audit_id),
  CONSTRAINT app_audit_logs_user_fk FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

CREATE INDEX app_audit_logs_created_ix ON app_audit_logs (created_at);
CREATE INDEX app_audit_logs_actor_ix ON app_audit_logs (actor);

CREATE TABLE app_request_history (
  request_id VARCHAR2(64) NOT NULL,
  user_id NUMBER,
  requested_by VARCHAR2(128) NOT NULL,
  action VARCHAR2(64) NOT NULL,
  db_name VARCHAR2(64) NOT NULL,
  status VARCHAR2(32) NOT NULL,
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  duration_ms NUMBER,
  payload_json CLOB NOT NULL,
  response_json CLOB,
  error_message VARCHAR2(2000),
  external_request_id VARCHAR2(128),
  CONSTRAINT app_request_history_pk PRIMARY KEY (request_id),
  CONSTRAINT app_request_history_user_fk FOREIGN KEY (user_id) REFERENCES app_users(user_id)
);

CREATE INDEX app_request_history_created_ix ON app_request_history (created_at);
CREATE INDEX app_request_history_by_user_ix ON app_request_history (requested_by);

CREATE TABLE app_alert_notifications (
  alert_id VARCHAR2(64) NOT NULL,
  source_name VARCHAR2(64) DEFAULT 'n8n' NOT NULL,
  alert_type VARCHAR2(64) DEFAULT 'tablespace' NOT NULL,
  db_name VARCHAR2(64) NOT NULL,
  tablespace_name VARCHAR2(128),
  object_name VARCHAR2(128),
  severity VARCHAR2(32) NOT NULL,
  alert_status VARCHAR2(32) DEFAULT 'pending_approval' NOT NULL,
  message_text CLOB NOT NULL,
  utilization_pct NUMBER,
  threshold_pct NUMBER,
  critical_pct NUMBER,
  used_gb NUMBER,
  free_gb NUMBER,
  extend_size_gb NUMBER,
  datafile_name VARCHAR2(512),
  workflow_run_id VARCHAR2(128),
  approval_url VARCHAR2(2000),
  reject_url VARCHAR2(2000),
  callback_url VARCHAR2(2000),
  created_by VARCHAR2(128) DEFAULT 'n8n' NOT NULL,
  approved_by VARCHAR2(128),
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  approved_at TIMESTAMP(6),
  completed_at TIMESTAMP(6),
  metadata_json CLOB,
  CONSTRAINT app_alert_notifications_pk PRIMARY KEY (alert_id),
  CONSTRAINT app_alert_notifications_sev_ck CHECK (severity IN ('info', 'warning', 'critical', 'error')),
  CONSTRAINT app_alert_notifications_status_ck CHECK (alert_status IN ('pending_approval', 'approved', 'rejected', 'completed', 'failed', 'acknowledged'))
);

CREATE INDEX app_alert_notifications_db_ix ON app_alert_notifications (db_name, alert_type, alert_status);
CREATE INDEX app_alert_notifications_created_ix ON app_alert_notifications (created_at);

CREATE OR REPLACE TRIGGER app_alert_notifications_bu_trg
BEFORE UPDATE ON app_alert_notifications
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- ============================================================
-- 3) Run metrics storage tables (app_check_runs removed)
-- ============================================================
-- All tables now use requested_by for user tracking instead of run_id

CREATE TABLE app_run_metrics (
  metric_row_id         NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  metric_name           VARCHAR2(128)   NOT NULL,
  metric_value_number   NUMBER,
  metric_value_text     VARCHAR2(4000),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_metrics_pk PRIMARY KEY (metric_row_id)
);
CREATE INDEX app_run_metrics_req_ix ON app_run_metrics (requested_by);
CREATE INDEX app_run_metrics_created_ix ON app_run_metrics (created_at);

CREATE TABLE app_run_trend_points (
  trend_row_id          NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  point_label           VARCHAR2(128),
  point_name            VARCHAR2(128)   NOT NULL,
  point_value_number    NUMBER,
  point_value_text      VARCHAR2(4000),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_trend_points_pk PRIMARY KEY (trend_row_id)
);
CREATE INDEX app_run_trend_points_req_ix ON app_run_trend_points (requested_by);
CREATE INDEX app_run_trend_points_created_ix ON app_run_trend_points (created_at);

CREATE TABLE app_run_tablespaces (
  tablespace_row_id     NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  db_name               VARCHAR2(64),
  tablespace_name       VARCHAR2(128),
  used_gb               NUMBER,
  free_gb               NUMBER,
  pct_used              NUMBER,
  tablespace_status     VARCHAR2(32),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_tablespaces_pk PRIMARY KEY (tablespace_row_id)
);
CREATE INDEX app_run_tablespaces_req_ix ON app_run_tablespaces (requested_by);
CREATE INDEX app_run_tablespaces_db_ix ON app_run_tablespaces (db_name);
CREATE INDEX app_run_tablespaces_created_ix ON app_run_tablespaces (created_at);

CREATE TABLE app_run_sessions (
  session_row_id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  sid                   NUMBER,
  serial_num            NUMBER,
  db_username           VARCHAR2(128),
  machine_name          VARCHAR2(255),
  program_name          VARCHAR2(255),
  session_status        VARCHAR2(32),
  wait_event            VARCHAR2(255),
  seconds_in_wait       NUMBER,
  sql_id                VARCHAR2(32),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_sessions_pk PRIMARY KEY (session_row_id)
);
CREATE INDEX app_run_sessions_req_ix ON app_run_sessions (requested_by);
CREATE INDEX app_run_sessions_created_ix ON app_run_sessions (created_at);

CREATE TABLE app_run_sql_metrics (
  sql_row_id            NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  sql_id                VARCHAR2(32),
  module_name           VARCHAR2(255),
  executions            NUMBER,
  elapsed_ms            NUMBER,
  cpu_ms                NUMBER,
  buffer_gets           NUMBER,
  sql_text              CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_sql_metrics_pk PRIMARY KEY (sql_row_id)
);
CREATE INDEX app_run_sql_metrics_req_ix ON app_run_sql_metrics (requested_by);
CREATE INDEX app_run_sql_metrics_created_ix ON app_run_sql_metrics (created_at);

CREATE TABLE app_run_locks (
  lock_row_id           NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  blocker_sid           NUMBER,
  waiter_sid            NUMBER,
  lock_object           VARCHAR2(255),
  wait_minutes          NUMBER,
  lock_mode             VARCHAR2(64),
  lock_payload_json     CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_locks_pk PRIMARY KEY (lock_row_id)
);
CREATE INDEX app_run_locks_req_ix ON app_run_locks (requested_by);
CREATE INDEX app_run_locks_created_ix ON app_run_locks (created_at);

CREATE TABLE app_run_backups (
  backup_row_id         NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  backup_external_id    VARCHAR2(128),
  backup_type           VARCHAR2(64),
  started_at            TIMESTAMP(6),
  duration_min          NUMBER,
  backup_status         VARCHAR2(32),
  compression_ratio     NUMBER,
  size_gb               NUMBER,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_backups_pk PRIMARY KEY (backup_row_id)
);
CREATE INDEX app_run_backups_req_ix ON app_run_backups (requested_by);
CREATE INDEX app_run_backups_created_ix ON app_run_backups (created_at);

CREATE TABLE app_run_alerts (
  alert_row_id          NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  alert_timestamp       TIMESTAMP(6),
  severity              VARCHAR2(32),
  message_text          CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_alerts_pk PRIMARY KEY (alert_row_id)
);
CREATE INDEX app_run_alerts_req_ix ON app_run_alerts (requested_by);
CREATE INDEX app_run_alerts_created_ix ON app_run_alerts (created_at);

CREATE TABLE app_run_invalid_objects (
  invalid_row_id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  owner_name            VARCHAR2(128),
  object_name           VARCHAR2(255),
  object_type           VARCHAR2(128),
  object_status         VARCHAR2(32),
  last_ddl_time         TIMESTAMP(6),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_invalid_objects_pk PRIMARY KEY (invalid_row_id)
);
CREATE INDEX app_run_invalid_objects_req_ix ON app_run_invalid_objects (requested_by);
CREATE INDEX app_run_invalid_objects_created_ix ON app_run_invalid_objects (created_at);

CREATE TABLE app_run_security_privileges (
  privilege_row_id      NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  grantee_name          VARCHAR2(128),
  privilege_name        VARCHAR2(255),
  risk_level            VARCHAR2(32),
  payload_json          CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_security_priv_pk PRIMARY KEY (privilege_row_id)
);
CREATE INDEX app_run_security_priv_req_ix ON app_run_security_privileges (requested_by);
CREATE INDEX app_run_security_priv_created_ix ON app_run_security_privileges (created_at);

CREATE TABLE app_run_findings (
  finding_row_id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  title                 VARCHAR2(500),
  detail                CLOB,
  severity              VARCHAR2(32),
  object_name           VARCHAR2(255),
  metric_name           VARCHAR2(128),
  metric_value          VARCHAR2(512),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_findings_pk PRIMARY KEY (finding_row_id)
);
CREATE INDEX app_run_findings_req_ix ON app_run_findings (requested_by);
CREATE INDEX app_run_findings_created_ix ON app_run_findings (created_at);

CREATE TABLE app_run_recommendations (
  recommendation_row_id NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  title                 VARCHAR2(500),
  detail                CLOB,
  severity              VARCHAR2(32),
  suggested_action      VARCHAR2(64),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_recommendations_pk PRIMARY KEY (recommendation_row_id)
);
CREATE INDEX app_run_recommendations_req_ix ON app_run_recommendations (requested_by);
CREATE INDEX app_run_recommendations_created_ix ON app_run_recommendations (created_at);

COMMIT;
PROMPT Tables recreated successfully without app_check_runs and run_id.

--------------------------------------------------------------------------------
-- 4) Bootstrap admin user (username: ARINDAM, password: Password123, token: Password123)
--------------------------------------------------------------------------------
MERGE INTO app_users dst
USING (
  SELECT
    'ARINDAM' AS username,
    'LOCAL-DEV-SALT-2026' AS salt_value
  FROM dual
) src
ON (dst.username = src.username)
WHEN MATCHED THEN
  UPDATE SET
    dst.password_salt = src.salt_value,
    dst.password_hash = LOWER(RAWTOHEX(STANDARD_HASH(src.salt_value || ':Password123', 'SHA256'))),
    dst.api_token_hash = LOWER(RAWTOHEX(STANDARD_HASH(src.salt_value || ':Password123', 'SHA256'))),
    dst.role = 'dba_admin',
    dst.is_active = 'Y',
    dst.failed_login_count = 0,
    dst.locked_until = NULL
WHEN NOT MATCHED THEN
  INSERT (
    username,
    password_salt,
    password_hash,
    api_token_hash,
    role,
    is_active
  )
  VALUES (
    src.username,
    src.salt_value,
    LOWER(RAWTOHEX(STANDARD_HASH(src.salt_value || ':Password123', 'SHA256'))),
    LOWER(RAWTOHEX(STANDARD_HASH(src.salt_value || ':Password123', 'SHA256'))),
    'dba_admin',
    'Y'
  );

COMMIT;

PROMPT Oracle application schema created successfully.
