SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--------------------------------------------------------------------------------
-- db_reboot_history
--
-- Purpose : Stores Oracle audit parameter snapshots captured during
--           PRODUCTION database start and stop operations.
--           One row per event:
--             PRE_SHUTDOWN       -- captured before SHUTDOWN, DB was OPEN
--             POST_MOUNT_COMPLIANT -- captured after STARTUP MOUNT, audit OK, DB opened
--             POST_MOUNT_FAILED    -- captured after STARTUP MOUNT, audit FAILED, DB aborted
--
-- Note    : n8n returns the raw V$PARAMETER values in the webhook response.
--           The application extracts them and inserts here. Only PROD databases
--           write to this table; DEV/UAT/DR events are not recorded.
--
-- Run as  : Application schema owner.
-- Idempotent: Safe to re-run.
--------------------------------------------------------------------------------

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'DB_REBOOT_HISTORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE db_reboot_history (
        id               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        db_name          VARCHAR2(100  CHAR) NOT NULL,
        environment      VARCHAR2(20   CHAR) NOT NULL,       -- PROD | DEV | UAT | DR
        event_type       VARCHAR2(30   CHAR) NOT NULL,
        -- PRE_SHUTDOWN         = captured before shutdown (DB was open)
        -- POST_MOUNT_COMPLIANT = all 5 audit params passed, DB opened
        -- POST_MOUNT_FAILED    = audit check failed, DB aborted
        requested_by     VARCHAR2(128  CHAR),
        captured_at      VARCHAR2(50   CHAR),                -- ISO string from Oracle SYSDATE on target DB
        spfile_value     VARCHAR2(500  CHAR),                -- blank = COMPLIANT (no spfile)
        audit_sys_ops    VARCHAR2(50   CHAR),                -- TRUE = COMPLIANT
        audit_trail      VARCHAR2(100  CHAR),                -- DB, EXTENDED = COMPLIANT
        db_name_param    VARCHAR2(100  CHAR),                -- value of db_name param
        is_compliant     CHAR(1        CHAR) DEFAULT 'Y' NOT NULL,
        failure_reasons  VARCHAR2(2000 CHAR),                -- null when compliant; semicolon-separated failures
        shutdown_option  VARCHAR2(30   CHAR),                -- IMMEDIATE | TRANSACTIONAL | ABORT (null for startup)
        created_at       TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

-- ── Idempotent column additions (for upgrades) ─────────────────────────────
DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name  = 'DB_REBOOT_HISTORY'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE db_reboot_history ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('id',              'id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('db_name',         'db_name VARCHAR2(100 CHAR)');
  add_column_if_missing('environment',     'environment VARCHAR2(20 CHAR)');
  add_column_if_missing('event_type',      'event_type VARCHAR2(30 CHAR)');
  add_column_if_missing('requested_by',    'requested_by VARCHAR2(128 CHAR)');
  add_column_if_missing('captured_at',     'captured_at VARCHAR2(50 CHAR)');
  add_column_if_missing('spfile_value',    'spfile_value VARCHAR2(500 CHAR)');
  add_column_if_missing('audit_sys_ops',   'audit_sys_ops VARCHAR2(50 CHAR)');
  add_column_if_missing('audit_trail',     'audit_trail VARCHAR2(100 CHAR)');
  add_column_if_missing('db_name_param',   'db_name_param VARCHAR2(100 CHAR)');
  add_column_if_missing('is_compliant',    q'[is_compliant CHAR(1 CHAR) DEFAULT 'Y']');
  add_column_if_missing('failure_reasons', 'failure_reasons VARCHAR2(2000 CHAR)');
  add_column_if_missing('shutdown_option', 'shutdown_option VARCHAR2(30 CHAR)');
  add_column_if_missing('created_at',      'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

-- ── Indexes ────────────────────────────────────────────────────────────────
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_DBR_HIST_DB_CREATED';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_dbr_hist_db_created ON db_reboot_history (db_name, created_at DESC)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_DBR_HIST_ENV';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_dbr_hist_env ON db_reboot_history (environment, created_at DESC)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_DBR_HIST_COMPLIANT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_dbr_hist_compliant ON db_reboot_history (is_compliant, created_at DESC)';
  END IF;
END;
/

COMMIT;

PROMPT db_reboot_history table created/upgraded.
PROMPT Run as application schema owner before deploying the updated General Admin audit compliance feature.
