SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--------------------------------------------------------------------------------
-- Approval Workflow for Protected PROD DBA Operations
--
-- Tables:
--   app_protected_actions       Registry of actions requiring approval on PROD
--   app_approval_requests       Pending/processed approval requests
--   app_approval_history        Immutable audit trail for every lifecycle event
--
-- Run as the application schema owner (APP_DBA) that owns APP_USERS,
-- APP_AUDIT_LOGS, and DATABASE_INVENTORY.
-- Idempotent: safe to re-run.
--------------------------------------------------------------------------------

-- ============================================================================
-- 1) APP_PROTECTED_ACTIONS — Registry of protected DBA actions
--    Adding a row here is the ONLY change needed to protect a new action.
-- ============================================================================
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_PROTECTED_ACTIONS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_protected_actions (
        action_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        action_name     VARCHAR2(64 CHAR)    NOT NULL,
        display_name    VARCHAR2(128 CHAR)   NOT NULL,
        category        VARCHAR2(64 CHAR)    DEFAULT 'user_management' NOT NULL,
        risk_level      VARCHAR2(16 CHAR)    DEFAULT 'high' NOT NULL,
        description     VARCHAR2(500 CHAR),
        is_active       CHAR(1 CHAR)         DEFAULT 'Y' NOT NULL,
        created_by      VARCHAR2(128 CHAR),
        created_at      TIMESTAMP(6)         DEFAULT SYSTIMESTAMP NOT NULL,
        updated_by      VARCHAR2(128 CHAR),
        updated_at      TIMESTAMP(6)         DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

-- Ensure all required columns exist (safe for re-runs)
DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_PROTECTED_ACTIONS'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_protected_actions ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('action_id',    'action_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('action_name',  'action_name VARCHAR2(64 CHAR)');
  add_column_if_missing('display_name', 'display_name VARCHAR2(128 CHAR)');
  add_column_if_missing('category',     q'[category VARCHAR2(64 CHAR) DEFAULT 'user_management']');
  add_column_if_missing('risk_level',   q'[risk_level VARCHAR2(16 CHAR) DEFAULT 'high']');
  add_column_if_missing('description',  'description VARCHAR2(500 CHAR)');
  add_column_if_missing('is_active',    q'[is_active CHAR(1 CHAR) DEFAULT 'Y']');
  add_column_if_missing('created_by',   'created_by VARCHAR2(128 CHAR)');
  add_column_if_missing('created_at',   'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('updated_by',   'updated_by VARCHAR2(128 CHAR)');
  add_column_if_missing('updated_at',   'updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

-- Constraints
DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists(q'[ALTER TABLE app_protected_actions ADD CONSTRAINT ck_prot_action_active   CHECK (is_active IN ('Y','N'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_protected_actions ADD CONSTRAINT ck_prot_action_risk     CHECK (risk_level IN ('low','medium','high','critical'))]');
END;
/

-- Indexes
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'UX_PROT_ACTION_NAME';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX ux_prot_action_name ON app_protected_actions (UPPER(action_name))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_PROT_ACTION_ACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE INDEX ix_prot_action_active ON app_protected_actions (is_active, category)]';
  END IF;
END;
/

-- Trigger: keep updated_at fresh
CREATE OR REPLACE TRIGGER trg_prot_action_biu
BEFORE INSERT OR UPDATE ON app_protected_actions
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.created_at IS NULL THEN
    :NEW.created_at := SYSTIMESTAMP;
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/


-- ============================================================================
-- 2) APP_APPROVAL_REQUESTS — Core approval request tracking
--    Stores the frozen webhook payload so it can be replayed exactly on
--    approval without any reconstruction logic.
-- ============================================================================
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_APPROVAL_REQUESTS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_approval_requests (
        request_id          VARCHAR2(64 CHAR)    NOT NULL,
        action_name         VARCHAR2(64 CHAR)    NOT NULL,
        display_name        VARCHAR2(128 CHAR)   NOT NULL,
        db_name             VARCHAR2(128 CHAR)   NOT NULL,
        environment         VARCHAR2(20 CHAR)    NOT NULL,
        requester_user_id   NUMBER               NOT NULL,
        requester_username  VARCHAR2(128 CHAR)   NOT NULL,
        request_status      VARCHAR2(20 CHAR)    DEFAULT 'pending' NOT NULL,
        risk_level          VARCHAR2(16 CHAR)    DEFAULT 'high' NOT NULL,
        reviewer_user_id    NUMBER,
        reviewer_username   VARCHAR2(128 CHAR),
        reviewer_comment    VARCHAR2(2000 CHAR),
        reviewed_at         TIMESTAMP(6),
        webhook_payload     CLOB                 NOT NULL,
        request_params      CLOB,
        execution_status    VARCHAR2(20 CHAR),
        execution_response  CLOB,
        executed_at         TIMESTAMP(6),
        expires_at          TIMESTAMP(6),
        created_at          TIMESTAMP(6)         DEFAULT SYSTIMESTAMP NOT NULL,
        updated_at          TIMESTAMP(6)         DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

-- Ensure all required columns exist (safe for re-runs)
DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_APPROVAL_REQUESTS'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_approval_requests ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('request_id',          'request_id VARCHAR2(64 CHAR)');
  add_column_if_missing('action_name',         'action_name VARCHAR2(64 CHAR)');
  add_column_if_missing('display_name',        'display_name VARCHAR2(128 CHAR)');
  add_column_if_missing('db_name',             'db_name VARCHAR2(128 CHAR)');
  add_column_if_missing('environment',         'environment VARCHAR2(20 CHAR)');
  add_column_if_missing('requester_user_id',   'requester_user_id NUMBER');
  add_column_if_missing('requester_username',  'requester_username VARCHAR2(128 CHAR)');
  add_column_if_missing('request_status',      q'[request_status VARCHAR2(20 CHAR) DEFAULT 'pending']');
  add_column_if_missing('risk_level',          q'[risk_level VARCHAR2(16 CHAR) DEFAULT 'high']');
  add_column_if_missing('reviewer_user_id',    'reviewer_user_id NUMBER');
  add_column_if_missing('reviewer_username',   'reviewer_username VARCHAR2(128 CHAR)');
  add_column_if_missing('reviewer_comment',    'reviewer_comment VARCHAR2(2000 CHAR)');
  add_column_if_missing('reviewed_at',         'reviewed_at TIMESTAMP(6)');
  add_column_if_missing('webhook_payload',     'webhook_payload CLOB');
  add_column_if_missing('request_params',      'request_params CLOB');
  add_column_if_missing('execution_status',    'execution_status VARCHAR2(20 CHAR)');
  add_column_if_missing('execution_response',  'execution_response CLOB');
  add_column_if_missing('executed_at',         'executed_at TIMESTAMP(6)');
  add_column_if_missing('expires_at',          'expires_at TIMESTAMP(6)');
  add_column_if_missing('created_at',          'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('updated_at',          'updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

-- Primary key and constraints
DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists('ALTER TABLE app_approval_requests ADD CONSTRAINT app_approval_requests_pk PRIMARY KEY (request_id)');
  add_constraint_ignore_exists('ALTER TABLE app_approval_requests ADD CONSTRAINT fk_approval_req_user   FOREIGN KEY (requester_user_id)  REFERENCES app_users(user_id)');
  add_constraint_ignore_exists('ALTER TABLE app_approval_requests ADD CONSTRAINT fk_approval_rev_user   FOREIGN KEY (reviewer_user_id)   REFERENCES app_users(user_id)');
  add_constraint_ignore_exists(q'[ALTER TABLE app_approval_requests ADD CONSTRAINT ck_approval_status     CHECK (request_status IN ('pending','approved','rejected','expired','cancelled'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_approval_requests ADD CONSTRAINT ck_approval_risk       CHECK (risk_level IN ('low','medium','high','critical'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_approval_requests ADD CONSTRAINT ck_approval_exec_status CHECK (execution_status IS NULL OR execution_status IN ('pending','executing','success','failed','skipped'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_approval_requests ADD CONSTRAINT ck_approval_env        CHECK (environment IN ('PROD','DR'))]');
END;
/

-- Indexes for common query patterns
DECLARE
  v_count NUMBER;
BEGIN
  -- Primary listing: pending approvals, ordered by creation time
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_REQ_STATUS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_req_status ON app_approval_requests (request_status, created_at)';
  END IF;

  -- Filter by database
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_REQ_DB';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_req_db ON app_approval_requests (db_name, request_status)';
  END IF;

  -- My requests (requester view)
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_REQ_USER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_req_user ON app_approval_requests (requester_user_id, created_at)';
  END IF;

  -- Action type filter
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_REQ_ACTION';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_req_action ON app_approval_requests (action_name, request_status)';
  END IF;

  -- Expiry check (for scheduled cleanup / auto-expire jobs)
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_REQ_EXPIRES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE INDEX ix_approval_req_expires ON app_approval_requests (expires_at, request_status)]';
  END IF;

  -- Chronological listing
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_REQ_CREATED';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_req_created ON app_approval_requests (created_at)';
  END IF;
END;
/

-- Trigger: keep updated_at fresh
CREATE OR REPLACE TRIGGER trg_approval_req_biu
BEFORE INSERT OR UPDATE ON app_approval_requests
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.created_at IS NULL THEN
    :NEW.created_at := SYSTIMESTAMP;
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/


-- ============================================================================
-- 3) APP_APPROVAL_HISTORY — Immutable audit trail for every state transition
--    Every action on a request (create, approve, reject, expire, execute,
--    execute_fail) creates a row. This table is append-only.
-- ============================================================================
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_APPROVAL_HISTORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_approval_history (
        history_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        request_id      VARCHAR2(64 CHAR)    NOT NULL,
        event_type      VARCHAR2(32 CHAR)    NOT NULL,
        actor_user_id   NUMBER,
        actor_username  VARCHAR2(128 CHAR)   NOT NULL,
        comment_text    VARCHAR2(2000 CHAR),
        snapshot_status VARCHAR2(20 CHAR)    NOT NULL,
        metadata_json   CLOB,
        created_at      TIMESTAMP(6)         DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

-- Ensure all required columns exist (safe for re-runs)
DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_APPROVAL_HISTORY'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_approval_history ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('history_id',      'history_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('request_id',      'request_id VARCHAR2(64 CHAR)');
  add_column_if_missing('event_type',      'event_type VARCHAR2(32 CHAR)');
  add_column_if_missing('actor_user_id',   'actor_user_id NUMBER');
  add_column_if_missing('actor_username',  'actor_username VARCHAR2(128 CHAR)');
  add_column_if_missing('comment_text',    'comment_text VARCHAR2(2000 CHAR)');
  add_column_if_missing('snapshot_status', 'snapshot_status VARCHAR2(20 CHAR)');
  add_column_if_missing('metadata_json',   'metadata_json CLOB');
  add_column_if_missing('created_at',      'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

-- Constraints
DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists('ALTER TABLE app_approval_history ADD CONSTRAINT fk_approval_hist_req    FOREIGN KEY (request_id)    REFERENCES app_approval_requests(request_id)');
  add_constraint_ignore_exists('ALTER TABLE app_approval_history ADD CONSTRAINT fk_approval_hist_actor  FOREIGN KEY (actor_user_id) REFERENCES app_users(user_id)');
  add_constraint_ignore_exists(q'[ALTER TABLE app_approval_history ADD CONSTRAINT ck_approval_hist_event  CHECK (event_type IN ('requested','approved','rejected','expired','cancelled','executing','executed','execute_failed'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_approval_history ADD CONSTRAINT ck_approval_hist_status CHECK (snapshot_status IN ('pending','approved','rejected','expired','cancelled'))]');
END;
/

-- Indexes
DECLARE
  v_count NUMBER;
BEGIN
  -- Timeline for a specific request
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_HIST_REQ';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_hist_req ON app_approval_history (request_id, created_at)';
  END IF;

  -- Actor audit trail
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_HIST_ACTOR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_hist_actor ON app_approval_history (actor_user_id, created_at)';
  END IF;

  -- Event type filter
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_HIST_EVENT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_hist_event ON app_approval_history (event_type, created_at)';
  END IF;

  -- Chronological listing
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_APPROVAL_HIST_CREATED';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_approval_hist_created ON app_approval_history (created_at)';
  END IF;
END;
/


-- ============================================================================
-- 4) VIEW: Pending approvals summary (used by the Admin → Pending Approvals UI)
-- ============================================================================
CREATE OR REPLACE VIEW app_vw_pending_approvals AS
SELECT
  r.request_id,
  r.action_name,
  r.display_name,
  r.db_name,
  r.environment,
  r.risk_level,
  r.requester_user_id,
  r.requester_username,
  r.request_status,
  r.request_params,
  r.reviewer_username,
  r.reviewer_comment,
  r.reviewed_at,
  r.execution_status,
  r.expires_at,
  r.created_at,
  r.updated_at,
  u.email AS requester_email
FROM app_approval_requests r
LEFT JOIN app_users u ON u.user_id = r.requester_user_id
ORDER BY
  CASE r.request_status WHEN 'pending' THEN 0 ELSE 1 END,
  r.created_at DESC;


-- ============================================================================
-- 5) Seed the initial protected actions
--    These four actions require approval when executed against PROD databases.
--    To protect a new action in the future, simply INSERT a new row here.
-- ============================================================================
MERGE INTO app_protected_actions dst
USING (
  SELECT 'drop_user'          AS action_name, 'Drop User'                 AS display_name, 'user_management' AS category, 'critical' AS risk_level, 'Permanently drop an Oracle user and all owned objects (CASCADE).'           AS description FROM dual UNION ALL
  SELECT 'change_default_tbs' AS action_name, 'Change Default Tablespace' AS display_name, 'user_management' AS category, 'high'     AS risk_level, 'Reassign a user''s default tablespace to a different one.'                   AS description FROM dual UNION ALL
  SELECT 'rename_user'        AS action_name, 'Rename User'               AS display_name, 'user_management' AS category, 'high'     AS risk_level, 'Rename an Oracle database user using ALTER USER ... RENAME TO.'             AS description FROM dual UNION ALL
  SELECT 'drop_profile'       AS action_name, 'Drop Profile'              AS display_name, 'user_management' AS category, 'critical' AS risk_level, 'Permanently remove an Oracle profile from the database.'                    AS description FROM dual
) src
ON (UPPER(dst.action_name) = UPPER(src.action_name))
WHEN NOT MATCHED THEN
  INSERT (action_name, display_name, category, risk_level, description, is_active, created_by)
  VALUES (src.action_name, src.display_name, src.category, src.risk_level, src.description, 'Y', 'SYSTEM');

COMMIT;

PROMPT ============================================================
PROMPT  Approval Workflow migration complete.
PROMPT
PROMPT  Tables created:
PROMPT    - app_protected_actions    (registry of protected actions)
PROMPT    - app_approval_requests    (approval request tracking)
PROMPT    - app_approval_history     (immutable audit trail)
PROMPT
PROMPT  View created:
PROMPT    - app_vw_pending_approvals (admin panel query)
PROMPT
PROMPT  Seed data:
PROMPT    - drop_user, change_default_tbs, rename_user, drop_profile
PROMPT ============================================================
