SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--------------------------------------------------------------------------------
-- DBA Console Module migration
--
-- Tables:
--   app_shift_sessions        DBA shift login/logout records
--   app_handovers             Shift handover notes + acknowledgement
--   app_backup_template       Master backup definitions (app_admin maintained)
--   app_db_status_checks      Per-DB per-shift database availability checks
--   app_backup_status_checks  Per-backup per-shift backup status checks
--   app_webhook_logs          n8n webhook dispatch audit log
--
-- Views:
--   app_vw_current_shift      Active shift sessions joined to users
--   app_vw_shift_attendance   Daily/monthly attendance rollup
--
-- Run as the application schema owner that owns APP_USERS and DATABASE_INVENTORY.
-- Idempotent: safe to re-run.
--------------------------------------------------------------------------------

DECLARE
  v_count NUMBER;
  PROCEDURE drop_constraint_if_exists(p_table VARCHAR2, p_constraint VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' DROP CONSTRAINT ' || p_constraint;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2443 THEN
        RAISE;
      END IF;
  END;
  PROCEDURE drop_index_if_exists(p_index VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX ' || p_index;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -1418 THEN
        RAISE;
      END IF;
  END;
BEGIN
  NULL;
END;
/

--------------------------------------------------------------------------------
-- app_shift_sessions
--------------------------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_SHIFT_SESSIONS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_shift_sessions (
        session_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        user_id       NUMBER NOT NULL,
        username      VARCHAR2(128 CHAR) NOT NULL,
        email         VARCHAR2(320 CHAR) NOT NULL,
        shift_number  NUMBER NOT NULL,
        shift_date    DATE NOT NULL,
        login_at      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        logout_at     TIMESTAMP(6),
        status        VARCHAR2(16 CHAR) DEFAULT 'ACTIVE' NOT NULL,
        is_active     CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        created_by    VARCHAR2(128 CHAR),
        created_at    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        updated_by    VARCHAR2(128 CHAR),
        updated_at    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_SHIFT_SESSIONS'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_shift_sessions ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('session_id',   'session_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('user_id',      'user_id NUMBER');
  add_column_if_missing('username',     'username VARCHAR2(128 CHAR)');
  add_column_if_missing('email',        'email VARCHAR2(320 CHAR)');
  add_column_if_missing('shift_number', 'shift_number NUMBER');
  add_column_if_missing('shift_date',   'shift_date DATE');
  add_column_if_missing('login_at',     'login_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('logout_at',    'logout_at TIMESTAMP(6)');
  add_column_if_missing('status',       q'[status VARCHAR2(16 CHAR) DEFAULT 'ACTIVE']');
  add_column_if_missing('is_active',    q'[is_active CHAR(1 CHAR) DEFAULT 'Y']');
  add_column_if_missing('created_by',   'created_by VARCHAR2(128 CHAR)');
  add_column_if_missing('created_at',   'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('updated_by',   'updated_by VARCHAR2(128 CHAR)');
  add_column_if_missing('updated_at',   'updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists('ALTER TABLE app_shift_sessions ADD CONSTRAINT fk_shift_session_user   FOREIGN KEY (user_id) REFERENCES app_users(user_id)');
  add_constraint_ignore_exists(q'[ALTER TABLE app_shift_sessions ADD CONSTRAINT ck_shift_session_shift  CHECK (shift_number IN (1,2,3))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_shift_sessions ADD CONSTRAINT ck_shift_session_status CHECK (status IN ('ACTIVE','CLOSED'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_shift_sessions ADD CONSTRAINT ck_shift_session_active CHECK (is_active IN ('Y','N'))]');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'UX_SHIFT_SESSION_ONE_ACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE UNIQUE INDEX ux_shift_session_one_active
      ON app_shift_sessions (
        CASE WHEN is_active = 'Y' THEN user_id END
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_SHIFT_SESSION_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_shift_session_shift ON app_shift_sessions (shift_number, shift_date)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_SHIFT_SESSION_ACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE INDEX ix_shift_session_active ON app_shift_sessions (is_active, login_at)]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_SHIFT_SESSION_USER';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_shift_session_user ON app_shift_sessions (user_id, login_at)';
  END IF;

  -- One active DBA per time-based shift (1,2,3). General Shift (4) allows multiple.
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'UX_SHIFT_SESSION_ONE_PER_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE UNIQUE INDEX ux_shift_session_one_per_shift
      ON app_shift_sessions (
        CASE WHEN is_active = 'Y' AND shift_number IN (1,2,3) THEN shift_number END
      )
    ]';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- app_handovers
--------------------------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_HANDOVERS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_handovers (
        handover_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        session_id       NUMBER NOT NULL,
        author_user_id   NUMBER NOT NULL,
        author_username  VARCHAR2(128 CHAR) NOT NULL,
        shift_number     NUMBER NOT NULL,
        shift_date       DATE NOT NULL,
        handover_text    CLOB NOT NULL,
        status           VARCHAR2(16 CHAR) DEFAULT 'PENDING' NOT NULL,
        ack_user_id      NUMBER,
        ack_username     VARCHAR2(128 CHAR),
        ack_at           TIMESTAMP(6),
        override_reason  VARCHAR2(500 CHAR),
        is_override      CHAR(1 CHAR) DEFAULT 'N' NOT NULL,
        created_by       VARCHAR2(128 CHAR),
        created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        updated_by       VARCHAR2(128 CHAR),
        updated_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_HANDOVERS'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_handovers ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('handover_id',     'handover_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('session_id',      'session_id NUMBER');
  add_column_if_missing('author_user_id',  'author_user_id NUMBER');
  add_column_if_missing('author_username', 'author_username VARCHAR2(128 CHAR)');
  add_column_if_missing('shift_number',    'shift_number NUMBER');
  add_column_if_missing('shift_date',      'shift_date DATE');
  add_column_if_missing('handover_text',   'handover_text CLOB');
  add_column_if_missing('status',          q'[status VARCHAR2(16 CHAR) DEFAULT 'PENDING']');
  add_column_if_missing('ack_user_id',     'ack_user_id NUMBER');
  add_column_if_missing('ack_username',    'ack_username VARCHAR2(128 CHAR)');
  add_column_if_missing('ack_at',          'ack_at TIMESTAMP(6)');
  add_column_if_missing('override_reason', 'override_reason VARCHAR2(500 CHAR)');
  add_column_if_missing('is_override',     q'[is_override CHAR(1 CHAR) DEFAULT 'N']');
  add_column_if_missing('created_by',      'created_by VARCHAR2(128 CHAR)');
  add_column_if_missing('created_at',      'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('updated_by',      'updated_by VARCHAR2(128 CHAR)');
  add_column_if_missing('updated_at',      'updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists('ALTER TABLE app_handovers ADD CONSTRAINT fk_handover_session FOREIGN KEY (session_id) REFERENCES app_shift_sessions(session_id)');
  add_constraint_ignore_exists('ALTER TABLE app_handovers ADD CONSTRAINT fk_handover_author  FOREIGN KEY (author_user_id) REFERENCES app_users(user_id)');
  add_constraint_ignore_exists('ALTER TABLE app_handovers ADD CONSTRAINT fk_handover_ack     FOREIGN KEY (ack_user_id) REFERENCES app_users(user_id)');
  add_constraint_ignore_exists(q'[ALTER TABLE app_handovers ADD CONSTRAINT ck_handover_status  CHECK (status IN ('PENDING','ACKNOWLEDGED'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_handovers ADD CONSTRAINT ck_handover_override CHECK (is_override IN ('Y','N'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_handovers ADD CONSTRAINT ck_handover_shift    CHECK (shift_number IN (1,2,3))]');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'UX_HANDOVER_ONE_PENDING';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE UNIQUE INDEX ux_handover_one_pending
      ON app_handovers (
        CASE WHEN status = 'PENDING' THEN session_id END
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_HANDOVER_SESSION';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_handover_session ON app_handovers (session_id)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_HANDOVER_PENDING';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE INDEX ix_handover_pending ON app_handovers (status, shift_date)]';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_HANDOVER_AUTHOR';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_handover_author ON app_handovers (author_user_id, shift_date)';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- app_backup_template
--------------------------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_BACKUP_TEMPLATE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_backup_template (
        backup_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        database_id    NUMBER NOT NULL,
        backup_name    VARCHAR2(128 CHAR) NOT NULL,
        scheduled_time VARCHAR2(8 CHAR),
        backup_type    VARCHAR2(32 CHAR),
        is_active      CHAR(1 CHAR) DEFAULT 'Y' NOT NULL,
        created_by     VARCHAR2(128 CHAR),
        created_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        updated_by     VARCHAR2(128 CHAR),
        updated_at     TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_BACKUP_TEMPLATE'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_backup_template ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('backup_id',      'backup_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('database_id',    'database_id NUMBER');
  add_column_if_missing('backup_name',    'backup_name VARCHAR2(128 CHAR)');
  add_column_if_missing('scheduled_time', 'scheduled_time VARCHAR2(8 CHAR)');
  add_column_if_missing('backup_type',    'backup_type VARCHAR2(32 CHAR)');
  add_column_if_missing('is_active',      q'[is_active CHAR(1 CHAR) DEFAULT 'Y']');
  add_column_if_missing('created_by',     'created_by VARCHAR2(128 CHAR)');
  add_column_if_missing('created_at',     'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('updated_by',     'updated_by VARCHAR2(128 CHAR)');
  add_column_if_missing('updated_at',     'updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists('ALTER TABLE app_backup_template ADD CONSTRAINT fk_backup_tpl_db    FOREIGN KEY (database_id) REFERENCES database_inventory(id)');
  add_constraint_ignore_exists(q'[ALTER TABLE app_backup_template ADD CONSTRAINT ck_backup_tpl_active CHECK (is_active IN ('Y','N'))]');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'UX_BACKUP_TPL_NAME';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX ux_backup_tpl_name ON app_backup_template (database_id, UPPER(backup_name))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_BACKUP_TPL_ACTIVE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[CREATE INDEX ix_backup_tpl_active ON app_backup_template (is_active, database_id)]';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- app_db_status_checks
--------------------------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_DB_STATUS_CHECKS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_db_status_checks (
        check_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        database_id      NUMBER NOT NULL,
        shift_number     NUMBER NOT NULL,
        shift_date       DATE NOT NULL,
        status           VARCHAR2(16 CHAR) NOT NULL,
        checked_by       NUMBER NOT NULL,
        checked_username VARCHAR2(128 CHAR) NOT NULL,
        checked_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        comment_text     VARCHAR2(1000 CHAR),
        created_by       VARCHAR2(128 CHAR),
        created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        updated_by       VARCHAR2(128 CHAR),
        updated_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_DB_STATUS_CHECKS'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_db_status_checks ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('check_id',         'check_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('database_id',      'database_id NUMBER');
  add_column_if_missing('shift_number',     'shift_number NUMBER');
  add_column_if_missing('shift_date',       'shift_date DATE');
  add_column_if_missing('status',           'status VARCHAR2(16 CHAR)');
  add_column_if_missing('checked_by',       'checked_by NUMBER');
  add_column_if_missing('checked_username', 'checked_username VARCHAR2(128 CHAR)');
  add_column_if_missing('checked_at',       'checked_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('comment_text',     'comment_text VARCHAR2(1000 CHAR)');
  add_column_if_missing('is_realtime_check','is_realtime_check VARCHAR2(1 CHAR) DEFAULT ''N''');
  add_column_if_missing('created_by',       'created_by VARCHAR2(128 CHAR)');
  add_column_if_missing('created_at',       'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('updated_by',       'updated_by VARCHAR2(128 CHAR)');
  add_column_if_missing('updated_at',       'updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists('ALTER TABLE app_db_status_checks ADD CONSTRAINT fk_dbchk_db   FOREIGN KEY (database_id) REFERENCES database_inventory(id)');
  add_constraint_ignore_exists('ALTER TABLE app_db_status_checks ADD CONSTRAINT fk_dbchk_user FOREIGN KEY (checked_by) REFERENCES app_users(user_id)');
  add_constraint_ignore_exists(q'[ALTER TABLE app_db_status_checks ADD CONSTRAINT ck_dbchk_status CHECK (status IN ('UP','DOWN','PARTIAL','MAINTENANCE'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_db_status_checks ADD CONSTRAINT ck_dbchk_shift  CHECK (shift_number IN (1,2,3))]');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'UX_DBCHK_UNIQUE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX ux_dbchk_unique ON app_db_status_checks (database_id, shift_number, TRUNC(shift_date))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_DBCHK_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_dbchk_shift ON app_db_status_checks (shift_number, shift_date)';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- app_backup_status_checks
--------------------------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_BACKUP_STATUS_CHECKS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_backup_status_checks (
        check_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        backup_id        NUMBER NOT NULL,
        database_id      NUMBER NOT NULL,
        shift_number     NUMBER NOT NULL,
        shift_date       DATE NOT NULL,
        status           VARCHAR2(16 CHAR) NOT NULL,
        checked_by       NUMBER NOT NULL,
        checked_username VARCHAR2(128 CHAR) NOT NULL,
        checked_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        comment_text     VARCHAR2(1000 CHAR),
        created_by       VARCHAR2(128 CHAR),
        created_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        updated_by       VARCHAR2(128 CHAR),
        updated_at       TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_BACKUP_STATUS_CHECKS'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_backup_status_checks ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('check_id',         'check_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('backup_id',        'backup_id NUMBER');
  add_column_if_missing('database_id',      'database_id NUMBER');
  add_column_if_missing('shift_number',     'shift_number NUMBER');
  add_column_if_missing('shift_date',       'shift_date DATE');
  add_column_if_missing('status',           'status VARCHAR2(16 CHAR)');
  add_column_if_missing('checked_by',       'checked_by NUMBER');
  add_column_if_missing('checked_username', 'checked_username VARCHAR2(128 CHAR)');
  add_column_if_missing('checked_at',       'checked_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('comment_text',     'comment_text VARCHAR2(1000 CHAR)');
  add_column_if_missing('created_by',       'created_by VARCHAR2(128 CHAR)');
  add_column_if_missing('created_at',       'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('updated_by',       'updated_by VARCHAR2(128 CHAR)');
  add_column_if_missing('updated_at',       'updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists('ALTER TABLE app_backup_status_checks ADD CONSTRAINT fk_bkchk_backup FOREIGN KEY (backup_id) REFERENCES app_backup_template(backup_id) ON DELETE CASCADE');
  add_constraint_ignore_exists('ALTER TABLE app_backup_status_checks ADD CONSTRAINT fk_bkchk_db     FOREIGN KEY (database_id) REFERENCES database_inventory(id)');
  add_constraint_ignore_exists('ALTER TABLE app_backup_status_checks ADD CONSTRAINT fk_bkchk_user   FOREIGN KEY (checked_by) REFERENCES app_users(user_id)');
  add_constraint_ignore_exists(q'[ALTER TABLE app_backup_status_checks ADD CONSTRAINT ck_bkchk_status CHECK (status IN ('SUCCESS','FAILED','RUNNING','NOT_STARTED','UNKNOWN'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_backup_status_checks ADD CONSTRAINT ck_bkchk_shift  CHECK (shift_number IN (1,2,3))]');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'UX_BKCHK_UNIQUE';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE UNIQUE INDEX ux_bkchk_unique ON app_backup_status_checks (backup_id, shift_number, TRUNC(shift_date))';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_BKCHK_SHIFT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_bkchk_shift ON app_backup_status_checks (shift_number, shift_date)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_BKCHK_DB';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_bkchk_db ON app_backup_status_checks (database_id, shift_date)';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- app_webhook_logs
--------------------------------------------------------------------------------
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_WEBHOOK_LOGS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_webhook_logs (
        log_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
        event_type    VARCHAR2(64 CHAR) NOT NULL,
        payload       CLOB,
        status_code   NUMBER,
        response_body CLOB,
        success       CHAR(1 CHAR) NOT NULL,
        error_msg     VARCHAR2(1000 CHAR),
        created_at    TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
      )
    ]';
  END IF;
END;
/

DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'APP_WEBHOOK_LOGS'
       AND column_name = UPPER(p_column_name);
    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_webhook_logs ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('log_id',        'log_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('event_type',    'event_type VARCHAR2(64 CHAR)');
  add_column_if_missing('payload',       'payload CLOB');
  add_column_if_missing('status_code',   'status_code NUMBER');
  add_column_if_missing('response_body', 'response_body CLOB');
  add_column_if_missing('success',       q'[success CHAR(1 CHAR)]');
  add_column_if_missing('error_msg',     'error_msg VARCHAR2(1000 CHAR)');
  add_column_if_missing('created_at',    'created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
END;
/

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_WEBHOOK_LOG_EVENT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_webhook_log_event ON app_webhook_logs (event_type, created_at)';
  END IF;
END;
/

--------------------------------------------------------------------------------
-- Triggers: keep updated_at fresh on UPDATE for audit-tracked tables
--------------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER trg_shift_session_biu
BEFORE INSERT OR UPDATE ON app_shift_sessions
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.created_at IS NULL THEN
    :NEW.created_at := SYSTIMESTAMP;
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_handover_biu
BEFORE INSERT OR UPDATE ON app_handovers
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.created_at IS NULL THEN
    :NEW.created_at := SYSTIMESTAMP;
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_backup_template_biu
BEFORE INSERT OR UPDATE ON app_backup_template
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.created_at IS NULL THEN
    :NEW.created_at := SYSTIMESTAMP;
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_db_status_check_biu
BEFORE INSERT OR UPDATE ON app_db_status_checks
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.created_at IS NULL THEN
    :NEW.created_at := SYSTIMESTAMP;
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE OR REPLACE TRIGGER trg_backup_status_check_biu
BEFORE INSERT OR UPDATE ON app_backup_status_checks
FOR EACH ROW
BEGIN
  IF INSERTING AND :NEW.created_at IS NULL THEN
    :NEW.created_at := SYSTIMESTAMP;
  END IF;
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

--------------------------------------------------------------------------------
-- Views
--------------------------------------------------------------------------------
CREATE OR REPLACE VIEW app_vw_current_shift AS
SELECT
  s.session_id,
  s.user_id,
  s.username,
  s.email,
  u.role AS user_role,
  s.shift_number,
  s.shift_date,
  s.login_at,
  s.logout_at,
  s.status,
  s.is_active
FROM app_shift_sessions s
JOIN app_users u ON u.user_id = s.user_id
WHERE s.is_active = 'Y'
ORDER BY s.login_at;

CREATE OR REPLACE VIEW app_vw_shift_attendance AS
SELECT
  TRUNC(login_at) AS attendance_date,
  shift_number,
  user_id,
  username,
  MIN(login_at)  AS first_login_at,
  MAX(logout_at) AS last_logout_at,
  COUNT(*)       AS session_count
FROM app_shift_sessions
WHERE status = 'CLOSED' OR (status = 'ACTIVE' AND logout_at IS NULL)
GROUP BY TRUNC(login_at), shift_number, user_id, username;

COMMIT;

--------------------------------------------------------------------------------
-- Upgrade: add General Shift (shift_number = 4)
-- General Shift can start/end any time; no handover required for logout.
-- Drop the old IN (1,2,3) check constraints and recreate with IN (1,2,3,4).
--------------------------------------------------------------------------------
DECLARE
  PROCEDURE drop_constraint_if_exists(p_table VARCHAR2, p_constraint VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' DROP CONSTRAINT ' || p_constraint;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE != -2443 THEN
        RAISE;
      END IF;
  END;
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  -- app_shift_sessions
  drop_constraint_if_exists('app_shift_sessions', 'CK_SHIFT_SESSION_SHIFT');
  add_constraint_ignore_exists(q'[ALTER TABLE app_shift_sessions ADD CONSTRAINT ck_shift_session_shift CHECK (shift_number IN (1,2,3,4))]');

  -- app_handovers
  drop_constraint_if_exists('app_handovers', 'CK_HANDOVER_SHIFT');
  add_constraint_ignore_exists(q'[ALTER TABLE app_handovers ADD CONSTRAINT ck_handover_shift CHECK (shift_number IN (1,2,3,4))]');

  -- app_db_status_checks
  drop_constraint_if_exists('app_db_status_checks', 'CK_DBCHK_SHIFT');
  add_constraint_ignore_exists(q'[ALTER TABLE app_db_status_checks ADD CONSTRAINT ck_dbchk_shift CHECK (shift_number IN (1,2,3,4))]');

  -- app_backup_status_checks
  drop_constraint_if_exists('app_backup_status_checks', 'CK_BKCHK_SHIFT');
  add_constraint_ignore_exists(q'[ALTER TABLE app_backup_status_checks ADD CONSTRAINT ck_bkchk_shift CHECK (shift_number IN (1,2,3,4))]');
END;
/

COMMIT;

PROMPT DBA Console migration complete.
PROMPT Tables created: app_shift_sessions, app_handovers, app_backup_template,
PROMPT   app_db_status_checks, app_backup_status_checks, app_webhook_logs.
PROMPT General Shift (shift_number=4) enabled — no handover required for logout.
