SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--------------------------------------------------------------------------------
-- Filesystem/Drive utilization support.
-- Prerequisite: db/oracle_app_setup.sql or db/oracle_alert_notifications.sql
-- has already created APP_ALERT_NOTIFICATIONS and APP_AUDIT_LOGS.
--------------------------------------------------------------------------------

DECLARE
  index_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO index_count
    FROM user_indexes
   WHERE index_name = 'APP_ALERT_NOTIFICATIONS_FS_IX';

  IF index_count = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE INDEX app_alert_notifications_fs_ix
         ON app_alert_notifications (alert_type, db_name, alert_status, created_at)';
  END IF;
END;
/

DECLARE
  table_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO table_count
    FROM user_tables
   WHERE table_name = 'APP_RUN_FILESYSTEM_USAGE';

  IF table_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_run_filesystem_usage (
        usage_row_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        requested_by    VARCHAR2(128) NOT NULL,
        db_name         VARCHAR2(64) NOT NULL,
        os_name         VARCHAR2(32),
        target_name     VARCHAR2(512) NOT NULL,
        filesystem_name VARCHAR2(512),
        mount_point     VARCHAR2(512),
        drive_name      VARCHAR2(64),
        size_gb         NUMBER,
        used_gb         NUMBER,
        free_gb         NUMBER,
        pct_used        NUMBER,
        pct_free        NUMBER,
        usage_status    VARCHAR2(32),
        payload_json    CLOB,
        created_at      TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
        CONSTRAINT app_run_filesystem_usage_pk PRIMARY KEY (usage_row_id),
        CONSTRAINT app_run_filesystem_usage_status_ck
          CHECK (usage_status IN ('healthy', 'warning', 'critical', 'unknown'))
      )
    ]';
  END IF;
END;
/

DECLARE
  index_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO index_count
    FROM user_indexes
   WHERE index_name = 'APP_RUN_FILESYSTEM_USAGE_DB_IX';

  IF index_count = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE INDEX app_run_filesystem_usage_db_ix
         ON app_run_filesystem_usage (db_name, created_at)';
  END IF;
END;
/

DECLARE
  index_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO index_count
    FROM user_indexes
   WHERE index_name = 'APP_RUN_FILESYSTEM_USAGE_REQ_IX';

  IF index_count = 0 THEN
    EXECUTE IMMEDIATE
      'CREATE INDEX app_run_filesystem_usage_req_ix
         ON app_run_filesystem_usage (requested_by, created_at)';
  END IF;
END;
/

COMMIT;

PROMPT Filesystem/Drive utilization database objects are ready.
