SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

-- ============================================================
-- CREATE STATEMENTS (app_check_runs removed, run_id removed)
-- ============================================================

CREATE TABLE app_alert_notifications (
  alert_id VARCHAR2(64) NOT NULL,
  source_name VARCHAR2(64) DEFAULT 'n8n' NOT NULL,
  alert_type VARCHAR2(64) DEFAULT 'tablespace' NOT NULL,
  db_name VARCHAR2(64) NOT NULL,
  tablespace_name VARCHAR2(128),
  object_name VARCHAR2(128),
  severity VARCHAR2(32) NOT NULL,
  alert_status VARCHAR2(32) DEFAULT 'pending_approval' NOT NULL,
  message_text CLOB NOT NULL,
  utilization_pct NUMBER,
  threshold_pct NUMBER,
  critical_pct NUMBER,
  used_gb NUMBER,
  free_gb NUMBER,
  extend_size_gb NUMBER,
  datafile_name VARCHAR2(512),
  workflow_run_id VARCHAR2(128),
  approval_url VARCHAR2(2000),
  reject_url VARCHAR2(2000),
  callback_url VARCHAR2(2000),
  created_by VARCHAR2(128) DEFAULT 'n8n' NOT NULL,
  approved_by VARCHAR2(128),
  created_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
  approved_at TIMESTAMP(6),
  completed_at TIMESTAMP(6),
  metadata_json CLOB,
  CONSTRAINT app_alert_notifications_pk PRIMARY KEY (alert_id),
  CONSTRAINT app_alert_notifications_sev_ck CHECK (severity IN ('info', 'warning', 'critical', 'error')),
  CONSTRAINT app_alert_notifications_status_ck CHECK (alert_status IN ('pending_approval', 'approved', 'rejected', 'completed', 'failed', 'acknowledged'))
);

CREATE INDEX app_alert_notifications_db_ix ON app_alert_notifications (db_name, alert_type, alert_status);
CREATE INDEX app_alert_notifications_created_ix ON app_alert_notifications (created_at);

CREATE OR REPLACE TRIGGER app_alert_notifications_bu_trg
BEFORE UPDATE ON app_alert_notifications
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

CREATE TABLE app_run_metrics (
  metric_row_id         NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  metric_name           VARCHAR2(128)   NOT NULL,
  metric_value_number   NUMBER,
  metric_value_text     VARCHAR2(4000),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_metrics_pk PRIMARY KEY (metric_row_id)
);
CREATE INDEX app_run_metrics_req_ix ON app_run_metrics (requested_by);
CREATE INDEX app_run_metrics_created_ix ON app_run_metrics (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_trend_points (
  trend_row_id          NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  point_label           VARCHAR2(128),
  point_name            VARCHAR2(128)   NOT NULL,
  point_value_number    NUMBER,
  point_value_text      VARCHAR2(4000),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_trend_points_pk PRIMARY KEY (trend_row_id)
);
CREATE INDEX app_run_trend_points_req_ix ON app_run_trend_points (requested_by);
CREATE INDEX app_run_trend_points_created_ix ON app_run_trend_points (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_tablespaces (
  tablespace_row_id     NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  db_name               VARCHAR2(64),
  tablespace_name       VARCHAR2(128),
  used_gb               NUMBER,
  free_gb               NUMBER,
  pct_used              NUMBER,
  tablespace_status     VARCHAR2(32),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_tablespaces_pk PRIMARY KEY (tablespace_row_id)
);
CREATE INDEX app_run_tablespaces_req_ix ON app_run_tablespaces (requested_by);
CREATE INDEX app_run_tablespaces_db_ix ON app_run_tablespaces (db_name);
CREATE INDEX app_run_tablespaces_created_ix ON app_run_tablespaces (created_at);

-- Migration: add db_name to existing app_run_tablespaces table
-- ALTER TABLE app_run_tablespaces ADD (db_name VARCHAR2(64));
-- CREATE INDEX app_run_tablespaces_db_ix ON app_run_tablespaces (db_name);

-- ------------------------------------------------------------

CREATE TABLE app_run_sessions (
  session_row_id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  sid                   NUMBER,
  serial_num            NUMBER,
  db_username           VARCHAR2(128),
  machine_name          VARCHAR2(255),
  program_name          VARCHAR2(255),
  session_status        VARCHAR2(32),
  wait_event            VARCHAR2(255),
  seconds_in_wait       NUMBER,
  sql_id                VARCHAR2(32),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_sessions_pk PRIMARY KEY (session_row_id)
);
CREATE INDEX app_run_sessions_req_ix ON app_run_sessions (requested_by);
CREATE INDEX app_run_sessions_created_ix ON app_run_sessions (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_sql_metrics (
  sql_row_id            NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  sql_id                VARCHAR2(32),
  module_name           VARCHAR2(255),
  executions            NUMBER,
  elapsed_ms            NUMBER,
  cpu_ms                NUMBER,
  buffer_gets           NUMBER,
  sql_text              CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_sql_metrics_pk PRIMARY KEY (sql_row_id)
);
CREATE INDEX app_run_sql_metrics_req_ix ON app_run_sql_metrics (requested_by);
CREATE INDEX app_run_sql_metrics_created_ix ON app_run_sql_metrics (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_locks (
  lock_row_id           NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  blocker_sid           NUMBER,
  waiter_sid            NUMBER,
  lock_object           VARCHAR2(255),
  wait_minutes          NUMBER,
  lock_mode             VARCHAR2(64),
  lock_payload_json     CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_locks_pk PRIMARY KEY (lock_row_id)
);
CREATE INDEX app_run_locks_req_ix ON app_run_locks (requested_by);
CREATE INDEX app_run_locks_created_ix ON app_run_locks (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_backups (
  backup_row_id         NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  backup_external_id    VARCHAR2(128),
  backup_type           VARCHAR2(64),
  started_at            TIMESTAMP(6),
  duration_min          NUMBER,
  backup_status         VARCHAR2(32),
  compression_ratio     NUMBER,
  size_gb               NUMBER,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_backups_pk PRIMARY KEY (backup_row_id)
);
CREATE INDEX app_run_backups_req_ix ON app_run_backups (requested_by);
CREATE INDEX app_run_backups_created_ix ON app_run_backups (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_alerts (
  alert_row_id          NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  alert_timestamp       TIMESTAMP(6),
  severity              VARCHAR2(32),
  message_text          CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_alerts_pk PRIMARY KEY (alert_row_id)
);
CREATE INDEX app_run_alerts_req_ix ON app_run_alerts (requested_by);
CREATE INDEX app_run_alerts_created_ix ON app_run_alerts (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_invalid_objects (
  invalid_row_id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  owner_name            VARCHAR2(128),
  object_name           VARCHAR2(255),
  object_type           VARCHAR2(128),
  object_status         VARCHAR2(32),
  last_ddl_time         TIMESTAMP(6),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_invalid_objects_pk PRIMARY KEY (invalid_row_id)
);
CREATE INDEX app_run_invalid_objects_req_ix ON app_run_invalid_objects (requested_by);
CREATE INDEX app_run_invalid_objects_created_ix ON app_run_invalid_objects (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_security_privileges (
  privilege_row_id      NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  grantee_name          VARCHAR2(128),
  privilege_name        VARCHAR2(255),
  risk_level            VARCHAR2(32),
  payload_json          CLOB,
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_security_priv_pk PRIMARY KEY (privilege_row_id)
);
CREATE INDEX app_run_security_priv_req_ix ON app_run_security_privileges (requested_by);
CREATE INDEX app_run_security_priv_created_ix ON app_run_security_privileges (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_findings (
  finding_row_id        NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  title                 VARCHAR2(500),
  detail                CLOB,
  severity              VARCHAR2(32),
  object_name           VARCHAR2(255),
  metric_name           VARCHAR2(128),
  metric_value          VARCHAR2(512),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_findings_pk PRIMARY KEY (finding_row_id)
);
CREATE INDEX app_run_findings_req_ix ON app_run_findings (requested_by);
CREATE INDEX app_run_findings_created_ix ON app_run_findings (created_at);

-- ------------------------------------------------------------

CREATE TABLE app_run_recommendations (
  recommendation_row_id NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY,
  requested_by          VARCHAR2(128)   NOT NULL,
  title                 VARCHAR2(500),
  detail                CLOB,
  severity              VARCHAR2(32),
  suggested_action      VARCHAR2(64),
  created_at            TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT app_run_recommendations_pk PRIMARY KEY (recommendation_row_id)
);
CREATE INDEX app_run_recommendations_req_ix ON app_run_recommendations (requested_by);
CREATE INDEX app_run_recommendations_created_ix ON app_run_recommendations (created_at);

COMMIT;
PROMPT Tables recreated successfully without app_check_runs and run_id.
