SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--------------------------------------------------------------------------------
-- DataPump Export/Import Templates and Job History Schema
-- Compatible with Oracle 19c / 21c / 23c
--------------------------------------------------------------------------------

PROMPT Creating DataPump tables and sequences...

-- 1) DataPump Export Templates Table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'DATAPUMP_EXPDP_TEMPLATES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE datapump_expdp_templates (
        template_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        template_name      VARCHAR2(128 CHAR) NOT NULL,
        database_name      VARCHAR2(128 CHAR),
        created_by         VARCHAR2(128 CHAR) NOT NULL,
        created_at         TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
        params_json        CLOB,
        dump_transfer_req  VARCHAR2(10 CHAR) DEFAULT 'no',
        transfer_server    VARCHAR2(128 CHAR),
        compression        VARCHAR2(50 CHAR),
        schemas_list       VARCHAR2(4000 CHAR),
        CONSTRAINT pk_datapump_expdp_templates PRIMARY KEY (template_id)
      )
    ]';
  END IF;
END;
/

-- 2) DataPump Import Templates Table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'DATAPUMP_IMPDP_TEMPLATES';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE datapump_impdp_templates (
        template_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        template_name      VARCHAR2(128 CHAR) NOT NULL,
        database_name      VARCHAR2(128 CHAR),
        created_by         VARCHAR2(128 CHAR) NOT NULL,
        created_at         TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
        params_json        CLOB,
        drop_user          VARCHAR2(10 CHAR) DEFAULT 'no',
        table_exists_action VARCHAR2(50 CHAR),
        content_type       VARCHAR2(50 CHAR),
        schemas_list       VARCHAR2(4000 CHAR),
        CONSTRAINT pk_datapump_impdp_templates PRIMARY KEY (template_id)
      )
    ]';
  END IF;
END;
/

-- 3) DataPump Job History Table
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'DATAPUMP_JOB_HISTORY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE datapump_job_history (
        job_id          VARCHAR2(50 CHAR) NOT NULL,
        operation       VARCHAR2(20 CHAR) NOT NULL,
        database_name   VARCHAR2(128 CHAR) NOT NULL,
        status          VARCHAR2(20 CHAR) DEFAULT 'running' NOT NULL,
        started_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
        completed_at    TIMESTAMP(6) WITH TIME ZONE,
        dump_file       VARCHAR2(500 CHAR),
        transfer_status VARCHAR2(500 CHAR),
        message         CLOB,
        requested_by    VARCHAR2(128 CHAR),
        params_json     CLOB,
        CONSTRAINT pk_datapump_job_history PRIMARY KEY (job_id)
      )
    ]';
  END IF;
END;
/

-- Indexes for fast lookup
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_DATAPUMP_JOB_STARTED';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_datapump_job_started ON datapump_job_history (started_at DESC)';
  END IF;
  
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_DATAPUMP_JOB_DB_STATUS';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_datapump_job_db_status ON datapump_job_history (database_name, status, started_at DESC)';
  END IF;
END;
/

COMMIT;
PROMPT DataPump tables script completed successfully.
