SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

--------------------------------------------------------------------------------
-- Change Audit Log migration
-- Tracks field-level changes for DATABASE_INVENTORY and APP_USERS tables.
-- Captures: who changed, when, what (old value → new value).
-- Run as the application schema owner.
-- Idempotent: safe to re-run.
--------------------------------------------------------------------------------

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_tables WHERE table_name = 'APP_CHANGE_AUDIT_LOG';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE app_change_audit_log (
        change_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        entity_type     VARCHAR2(32 CHAR)   NOT NULL,
        entity_id       NUMBER              NOT NULL,
        entity_name     VARCHAR2(256 CHAR),
        action          VARCHAR2(16 CHAR)   NOT NULL,
        changed_by      VARCHAR2(128 CHAR)  NOT NULL,
        changed_at      TIMESTAMP(6)        DEFAULT SYSTIMESTAMP NOT NULL,
        field_name      VARCHAR2(64 CHAR),
        old_value       VARCHAR2(4000 CHAR),
        new_value       VARCHAR2(4000 CHAR),
        change_summary  VARCHAR2(4000 CHAR),
        CONSTRAINT pk_change_audit_log PRIMARY KEY (change_id)
      )
    ]';
  END IF;
END;
/

-- Ensure all expected columns exist (safe for re-runs / upgrades)
DECLARE
  v_count NUMBER;
  PROCEDURE add_column_if_missing(p_column_name VARCHAR2, p_column_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
    INTO v_count
    FROM user_tab_columns
    WHERE table_name = 'APP_CHANGE_AUDIT_LOG'
      AND column_name = UPPER(p_column_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE app_change_audit_log ADD (' || p_column_sql || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('change_id',      'change_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY');
  add_column_if_missing('entity_type',    'entity_type VARCHAR2(32 CHAR)');
  add_column_if_missing('entity_id',      'entity_id NUMBER');
  add_column_if_missing('entity_name',    'entity_name VARCHAR2(256 CHAR)');
  add_column_if_missing('action',         'action VARCHAR2(16 CHAR)');
  add_column_if_missing('changed_by',     'changed_by VARCHAR2(128 CHAR)');
  add_column_if_missing('changed_at',     'changed_at TIMESTAMP(6) DEFAULT SYSTIMESTAMP');
  add_column_if_missing('field_name',     'field_name VARCHAR2(64 CHAR)');
  add_column_if_missing('old_value',      'old_value VARCHAR2(4000 CHAR)');
  add_column_if_missing('new_value',      'new_value VARCHAR2(4000 CHAR)');
  add_column_if_missing('change_summary', 'change_summary VARCHAR2(4000 CHAR)');
END;
/

-- Constraints
DECLARE
  PROCEDURE add_constraint_ignore_exists(p_sql VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql;
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE NOT IN (-2260, -2261, -2264, -2275) THEN
        RAISE;
      END IF;
  END;
BEGIN
  add_constraint_ignore_exists(q'[ALTER TABLE app_change_audit_log ADD CONSTRAINT ck_change_audit_entity_type CHECK (entity_type IN ('DATABASE_INVENTORY', 'APP_USER'))]');
  add_constraint_ignore_exists(q'[ALTER TABLE app_change_audit_log ADD CONSTRAINT ck_change_audit_action CHECK (action IN ('CREATE', 'UPDATE', 'DELETE', 'TOGGLE_STATUS'))]');
END;
/

-- Indexes
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_CHANGE_AUDIT_ENTITY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_change_audit_entity ON app_change_audit_log (entity_type, entity_id, changed_at DESC)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_CHANGE_AUDIT_CHANGED_AT';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_change_audit_changed_at ON app_change_audit_log (changed_at DESC)';
  END IF;

  SELECT COUNT(*) INTO v_count FROM user_indexes WHERE index_name = 'IX_CHANGE_AUDIT_CHANGED_BY';
  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE INDEX ix_change_audit_changed_by ON app_change_audit_log (changed_by)';
  END IF;
END;
/

COMMIT;

PROMPT Change Audit Log migration complete.
PROMPT Table created: APP_CHANGE_AUDIT_LOG
PROMPT Tracks field-level changes for DATABASE_INVENTORY and APP_USER entities.
