SET DEFINE OFF;
WHENEVER SQLERROR EXIT FAILURE ROLLBACK;

-- ============================================================
-- Table: performance_run_all_hist
-- Purpose : Stores one row per RUN ALL execution triggered from
--           the Performance Tuning section of the app.
--           n8n inserts a row after running all 8 checks and
--           getting the LLM summary.  The app reads the latest
--           row for the selected db_name to render the result.
-- ============================================================

CREATE TABLE performance_run_all_hist (
  run_id           NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY,
  db_name          VARCHAR2(64)   NOT NULL,
  environment      VARCHAR2(32),
  os               VARCHAR2(64),
  refreshed_by     VARCHAR2(128)  NOT NULL,
  -- Full JSON blob containing every query result set
  -- Structure expected by the app:
  --   { "top_sql": [...], "cpu_usage": [...], "wait_events": [...],
  --     "session_longops": [...], "invalid_obejcts": [...],
  --     "session_list": [...], "lock_check": [...], "long_queries": [...] }
  metrics_payload  CLOB,
  -- Free-text AI narrative produced by the LLM node in n8n
  ai_summary       CLOB,
  created_at       TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT perf_run_all_hist_pk PRIMARY KEY (run_id)
);

-- Index for fast "latest run per db" look-up
CREATE INDEX perf_run_all_hist_db_ts_ix
  ON performance_run_all_hist (db_name, created_at DESC);

-- Index for audit / refreshed_by queries
CREATE INDEX perf_run_all_hist_by_ix
  ON performance_run_all_hist (refreshed_by, created_at DESC);

-- Optional: keep only the last 90 days automatically (comment out if not wanted)
-- ALTER TABLE performance_run_all_hist
--   ADD CONSTRAINT perf_run_all_hist_expiry
--   CHECK (created_at > SYSTIMESTAMP - INTERVAL '90' DAY);

COMMIT;
PROMPT Table performance_run_all_hist created successfully.
